version: '3.9'
services:
  sgu-prae-service:
    image: sgu-prae-service
    build: .
    ports:
      - "8082:8082"
    container_name: sgu-prae-service
    command: mvn spring-boot:run
    networks:
      - sgu-networks
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://sgu-prae-db:5432/prae
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      sgu-prae-db:
        condition: service_healthy
    volumes:
      - ./storage:/app/storage

  sgu-prae-db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: prae
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: America/Sao_Paulo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d prae"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5435:5432"
    networks:
      - sgu-networks
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg-data:
    driver: local

networks:
  sgu-networks:
    external: true